# ----------- #
# MAIN PATHS: #
# ----------- #
repository_path: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/
data_path: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/
# repository_path: /home/maiso/cbu/repositories/alternate-level-of-care-project
# data_path: /home/maiso/cbu/data

# ---

# SAVED MODELS
balanced_random_forest_path: ["$repository_path", "checkpoints/balanced_random_forest.joblib"]
balanced_random_forest_metrics: ["$repository_path", "results/balanced_random_forest_metrics.csv"]

# Pytorch MLP
pytorch_mlp_results: ["$repository_path", "results/pytorch_mlp.csv"]
pytorch_mlp_log: ["$repository_path", "log/pytorch_mlp.log"]
pytorch_mlp_model_configurations: ["$repository_path", "config/pytorch_mlp.json"]
pytorch_temp_checkpoint: ["$repository_path", "checkpoints/temp_checkpoint.pth"]


# LOG
system_log: ["$repository_path", "log/system.log"]
logreg_log: ["$repository_path", "log/logistic_regression.log"]
nn_log: ["$repository_path", "log/neural_networks.log"]
creating_database_log: ["$repository_path", "log/creating_database.log"]
creating_held_out_log: ["$repository_path", "log/creating_heldout.log"]
building_diag_interv_map_log: ["$repository_path", "log/building_diag_interv_map.log"]
all_experiments_log: ["$repository_path", "log/all_experiments.log"]


# Output results
surrogate_models_results: ["$repository_path", "results/surrogate_models_results.csv"]
logreg_results: ["$repository_path", "results/logistic_regression.csv"]
logreg_latex: ["$repository_path", "results/logistic_regression.tex"]
latex_tables: ["$repository_path", "results/tables.tex"]
figures_folder: ["$repository_path", "results/figures/"]
experiment_results: ["$repository_path", "results/experiments_results.csv"]
custom_conf_results: ["$repository_path", "results/custom_conf_results.csv"]

experiment_results_cv: ["$repository_path", "results/experiments_results_cv.csv"]
custom_conf_results_cv: ["$repository_path", "results/custom_conf_results_cv.csv"]

#FIGURES
surrogate_decision_tree_figure: ["$figures_folder", "surrogate_decision_tree.jpg"]

numerical_variables_plot: ["$figures_folder", "numerical_variables_plot.jpg"]

# Gensim
gensim_model_folder: ["$repository_path", "gensim/models/"]
gensim_results_folder: ["$repository_path", "gensim/results/"]
gensim_log: ["$repository_path", "log/gensim.log"]
gensim_config: ["$repository_path", "config/gensim.json"]


# Input and Output
json_file: ["$data_path", "2015_2022/full_database.json"]
train_val_json: ["$data_path", "2015_2022/train_validation.json"]
heldout_json: ["$data_path", "2015_2022/heldout.json"]
unused_after_heldout_json: ["$data_path", "2015_2022/unused_after_held_out.json"]
encrypted_train_val_json: ["$data_path", "2015_2022/train_validation.json.encryption"]
encrypted_heldout_json: ["$data_path", "2015_2022/heldout.json.encryption"]


unified_merged_file_cz: ["$data_path", "2015_2022/full_cz_database.csv"]
unified_merged_file_noncz: ["$data_path", "2015_2022/full_noncz_database.csv"]
unified_merged_file: ["$data_path", "2015_2022/full_database.csv"]


# Only output:
diagnosis_dict: ["$data_path", "2015_2022/diagnosis_dict.json"]
intervention_dict: ["$data_path", "2015_2022/intervention_dict.json"]


# Partial Dependency Plots
ppd_age_figure: ["$figures_folder", "PDP_age.jpg"]
ppd_case_weight_figure: ["$figures_folder", "PDP_case_weight.jpg"]
ppd_cmg_figure: ["$figures_folder", "PDP_cmg.jpg"]
ppd_acute_days_figure: ["$figures_folder", "PDP_acute_days.jpg"]
ppd_alc_days_figure: ["$figures_folder", "PDP_alc_days.jpg"]



# Guideline DTs performances
guideline_dts_performances: ["$repository_path", "results/guideline_dts_performances.csv"]
guidelines_dts_figures: ["$figures_folder", "guideline_dts"]


# Permutation Feature Importance
permutation_feature_importance_results: ["$repository_path", "results/permutation_feature_importance.csv"]


# Surrogate LogReg Coefficient importance dataframe
surrogate_logreg_coefficients: ["$repository_path", "results/surrogate_logreg_coefficients.csv"]

# Latests results
explainable_logreg_coefficients: ["$repository_path", "results/explainable_logreg_coefficients.csv"]
explainable_logreg_coefficients_with_pvalues: ["$repository_path", "results/explainable_logreg_coefficients_with_pvalues.csv"]

explainable_logreg_metrics: ["$repository_path", "results/explainable_logreg_metrics.csv"]
explainable_logreg_model: ["$repository_path", "checkpoints/explainable_logreg.joblib"]

explainable_logit_metrics: ["$repository_path", "results/explainable_logit_metrics.csv"]
explainable_logit_coefficients: ["$repository_path", "results/explainable_logit_coefficients.csv"]


intervention_and_diagnosis_frequencies: ["$repository_path", "results/intervention_and_diagnosis_frequencies.csv"]


explainable_dt_metrics: ["$repository_path", "results/explainable_dt_metrics.csv"]
explainable_dt_figures: ["$figures_folder", "explainable_decision_tree.jpg"]

feature_ranking_plot: ["$figures_folder", "feature_ranking_plot.jpg"]


shap_on_brf_figures: ["$figures_folder", "shap_on_brf_figures.jpg"]
brf_on_shap_metrics: ["$repository_path", "results/brf_on_shap_metrics.csv"]
pdp_model_performance: ["$repository_path", "results/pdp_model_performance.csv"]


custom_explainable_dt_metrics: ["$repository_path", "results/custom_explainable_dt_metrics.csv"]
custon_explainable_dt_figures: ["$figures_folder", "custon_explainable_dt_figures.jpg"]



# BRF with cat and num 
permutation_brf_with_cat_and_num: ["$repository_path", "results/permutation_brf_with_cat_and_num.csv"]
permutation_brf_all_features: ["$repository_path", "results/permutation_brf_all_features.csv"]

# Only input
keyfile: ["$repository_path", "config/alc.key"]
housing_data: ["$data_path", "california-housing/housing.pickle"]

experiments_config: ["$repository_path", "config/experiment_configuration.json"]
models_config: ["$repository_path", "config/models.json"]

cz_files:
 - 2015/ALC Machine 2015Q1 - coded HCN.csv
 - 2015/ALC Machine 2015Q2 - coded HCN.csv
 - 2015/ALC Machine 2015Q3 - coded HCN.csv
 - 2015/ALC Machine 2015Q4 - coded HCN.csv
 - 2016/ALC Machine 2016Q1 - coded HCN.csv
 - 2016/ALC Machine 2016Q2 - coded HCN.csv
 - 2016/ALC Machine 2016Q3 - coded HCN.csv
 - 2016/ALC Machine 2016Q4 - coded HCN.csv
 - 2017/ALC Machine 2017Q1 - coded HCN.csv
 - 2017/ALC Machine 2017Q2 - coded HCN.csv
 - 2017/ALC Machine 2017Q3 - coded HCN.csv
 - 2017/ALC Machine 2017Q4 - coded HCN.csv
 - 2018/ALC Machine 2018Q1 - coded HCN.csv
 - 2018/ALC Machine 2018Q2 - coded HCN.csv
 - 2018/ALC Machine 2018Q3 - coded HCN.csv
 - 2018/ALC Machine 2018Q4 - coded HCN.csv
 - 2019/ALC Machine 2019Q1 - coded HCN.csv
 - 2019/ALC Machine 2019Q2 - coded HCN.csv
 - 2019/ALC Machine 2019Q3 - coded HCN.csv
 - 2019/ALC Machine 2019Q4 - coded HCN.csv
 - 2020/ALC Machine 2020Q1 - coded HCN.csv
 - 2020/ALC Machine 2020Q2 - coded HCN.csv
 - 2020/ALC Machine 2020Q3 - coded HCN.csv
 - 2020/ALC Machine 2020Q4 - coded HCN.csv
 - 2021/ALC Machine 2021Q1 - coded HCN.csv
 - 2021/ALC Machine 2021Q2 - coded HCN.csv
 - 2021/ALC Machine 2021Q3 - coded HCN.csv
 - 2021/ALC Machine 2021Q4 - coded HCN.csv
 - 2022/ALC Machine 2022Q1 - coded HCN.csv
 - 2022/ALC Machine 2022Q2 - coded HCN.csv
 - 2022/ALC Machine 2022Q3 - coded HCN.csv
 - 2022/ALC Machine 2022Q4 - coded HCN.csv

noncz_files:
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q1.csv
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q2.csv
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q3.csv
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q4.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q1.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q2.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q3.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q4.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q1.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q2.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q3.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q4.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q1.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q2.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q3.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q4.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q1.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q2.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q3.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q4.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q1.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q2.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q3.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q4.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q1.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q2.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q3.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q4.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q1.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q2.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q3.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q4.csv