# Logs
system_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/system.log
logreg_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/logistic_regression.log
nn_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/neural_networks.log
creating_database_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/creating_database.log
creating_held_out_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/creating_heldout.log
building_diag_interv_map_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/building_diag_interv_map.log
all_experiments_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/all_experiments.log

# Output results
logreg_results: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/results/logistic_regression.csv
logreg_latex: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/results/logistic_regression.tex
latex_tables: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/results/tables.tex
figures_folder: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/figures/
experiment_results: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/results/experiments_results.csv

# Gensim
gensim_model_folder: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/gensim/models/
gensim_results_folder: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/gensim/results/
gensim_log: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/log/gensim.log
gensim_config: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/config/gensim.json


# Input and Output
json_file: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/full_database.json
train_val_json: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/train_validation.json
heldout_json: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/heldout.json
unused_after_heldout_json: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/unused_after_held_out.json


unified_merged_file_cz: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/full_cz_database.csv
unified_merged_file_noncz: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/full_noncz_database.csv
unified_merged_file: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/full_database.csv
data_path: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/

# Only output:
diagnosis_dict: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/diagnosis_dict.json
intervention_dict: /Users/marianomaisonnave/Documents/CBU Postdoc/Grant Data/Merged/2015_2022/intervention_dict.json 

# Only input
experiments_config: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/config/experiment_configuration.json
models_config: /Users/marianomaisonnave/Repositories/alternate-level-of-care-project/config/models.json

cz_files:
 - 2015/ALC Machine 2015Q1 - coded HCN.csv
 - 2015/ALC Machine 2015Q2 - coded HCN.csv
 - 2015/ALC Machine 2015Q3 - coded HCN.csv
 - 2015/ALC Machine 2015Q4 - coded HCN.csv
 - 2016/ALC Machine 2016Q1 - coded HCN.csv
 - 2016/ALC Machine 2016Q2 - coded HCN.csv
 - 2016/ALC Machine 2016Q3 - coded HCN.csv
 - 2016/ALC Machine 2016Q4 - coded HCN.csv
 - 2017/ALC Machine 2017Q1 - coded HCN.csv
 - 2017/ALC Machine 2017Q2 - coded HCN.csv
 - 2017/ALC Machine 2017Q3 - coded HCN.csv
 - 2017/ALC Machine 2017Q4 - coded HCN.csv
 - 2018/ALC Machine 2018Q1 - coded HCN.csv
 - 2018/ALC Machine 2018Q2 - coded HCN.csv
 - 2018/ALC Machine 2018Q3 - coded HCN.csv
 - 2018/ALC Machine 2018Q4 - coded HCN.csv
 - 2019/ALC Machine 2019Q1 - coded HCN.csv
 - 2019/ALC Machine 2019Q2 - coded HCN.csv
 - 2019/ALC Machine 2019Q3 - coded HCN.csv
 - 2019/ALC Machine 2019Q4 - coded HCN.csv
 - 2020/ALC Machine 2020Q1 - coded HCN.csv
 - 2020/ALC Machine 2020Q2 - coded HCN.csv
 - 2020/ALC Machine 2020Q3 - coded HCN.csv
 - 2020/ALC Machine 2020Q4 - coded HCN.csv
 - 2021/ALC Machine 2021Q1 - coded HCN.csv
 - 2021/ALC Machine 2021Q2 - coded HCN.csv
 - 2021/ALC Machine 2021Q3 - coded HCN.csv
 - 2021/ALC Machine 2021Q4 - coded HCN.csv
 - 2022/ALC Machine 2022Q1 - coded HCN.csv
 - 2022/ALC Machine 2022Q2 - coded HCN.csv
 - 2022/ALC Machine 2022Q3 - coded HCN.csv
 - 2022/ALC Machine 2022Q4 - coded HCN.csv

noncz_files:
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q1.csv
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q2.csv
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q3.csv
 - 2015/2015 Non CZ - coded HCN/noncz 2015Q4.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q1.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q2.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q3.csv
 - 2016/2016 Non CZ - coded HCN/noncz 2016Q4.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q1.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q2.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q3.csv
 - 2017/2017 Non CZ - coded HCN/noncz 2017Q4.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q1.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q2.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q3.csv
 - 2018/2018 Non CZ - coded HCN/noncz 2018Q4.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q1.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q2.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q3.csv
 - 2019/2019 Non CZ - coded HCN/noncz 2019Q4.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q1.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q2.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q3.csv
 - 2020/2020 Non CZ - coded HCN/noncz 2020Q4.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q1.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q2.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q3.csv
 - 2021/2021 Non CZ - coded HCN/noncz 2021Q4.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q1.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q2.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q3.csv
 - 2022/2022 Non CZ - coded HCN/noncz 2022Q4.csv